# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HaiLuoQianBao' do

	pod 'Masonry'
    pod 'KSGuaidView'
    pod 'AXWebViewController'
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCSecurityPlugins'
end
